### PR TITLE
Create RPMs and DEBs for Centos/RHEL, Debian, Fedora, and test them

### PR DESCRIPTION
**Pull request by alanfranz**

### CODE REVIEW

**Comment by cavemandaveman** [comment]
What is the status on this?
It would be _very_ useful on projects that don't use Alpine yet!

**Comment by alanfranz** [comment]
@cavemandaveman if you take a look at my fork, you have everything ready to build for most distros. If you've got a linux with docker enabled, you can build them right now.

**Comment by ncopa** [comment]
How do i build the packages? just `cd packaging/$distro && bash build`?

**Comment by alanfranz** [comment]
if you've got docker installed, it's just a matter of:

```cd packaging/$distro && ./build```

it will build the package and run the tests.

**Comment by itamarjp** [comment]
Someone submitted it for review and inclusion in Fedora and EPEL 

https://bugzilla.redhat.com/show_bug.cgi?id=1393044

**Comment by tnguyen14** [comment]
Is there any update on this?

**Comment by alanfranz** [comment]
I think we can close this, it's not needed anymore (or maybe not interesting)

**Pull request closed without merging**
